export const TOKEN_CHANGE = "token_change"
export const LANGUAGE_CODE = "language_code"
export const LANGUAGE_CHANGE = "language_change"
export const USERINFO_CHANGE = "userinfo_change"
export const USERMESSAGE_CHANGE = "usermessage_change"
